services:
  react-app:
    container_name: finviz-test-app-web
    build:
      context: ./src/Finviz.TestApp.Web
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:31337
    ports:
      - "5173:80"
    restart: unless-stopped
    labels:
      type: frontend