services:
  api:
    container_name: finviz-test-app-api
    build:
      dockerfile: ./src/Finviz.TestApp.ImageNet.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: ${CONNECTIONSTRINGS__DEFAULT}
    depends_on:
      - postgres
    ports:
      - "31337:8080"
    labels:
      type: backend